[package]
name = "font_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustybuzz = "0.11.0"
ttf2mesh = { path = "/Users/yuta/ghq/github.com/higumachan/ttf2mesh-rs" }
